[package]
name = "tapssp-project"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
zeroize = "1"
rand = "0.8"
aes-gcm = "0.10"
keyring = "2"
thiserror = "1"
base64 = "0.21"

